### ISSUE TITLE
Запустить обновление агента из самого агента?

### ISSUE THREAD

**Issue by SergeBrick** [VladimirKosyuk/Zabbix_agent_update_and_install#1]
Спасибо, за Ваш проект. Очень интересно. 
Скажите,, возможно ли запустить обновление агента zabbix из самого агента.
Не хотелось бы использовать планировщик.

**Comment by VladimirKosyuk** [comment]
Насколько знаю, в агенте есть функционал remote command, можно рассмотреть его в качестве push. Но его механика - это такой же планировщик - при соблюдении определенного условия происходит выполнение определенного действия.
Если не секрет - почему не хотите использовать task sched?

**Comment by SergeBrick** [comment]
Мы обслуживаем сервера, на которых встречаются не совсем опытные администраторы.
Стараемся, чтобы лишняя информация, не вводила их в замешательство.
Не могли бы Вы попробовать реализовать автоматического обновление агента,, без планировщика? Работа будет оплачена. Для связи telegram @Serge_Brick Спасибо

**Comment by VladimirKosyuk** [comment]
Согласно [документации](https://www.zabbix.com/documentation/4.0/manual/config/notifications/action/operation/remote_command), Remote commands do not work with active Zabbix agents. Также, подразумевается, что скрипт обновления агента находится на обновляемом хосте, а политика выполнения скриптов не должна быть Restricted и у у\з заббикса на хосте должны быть права на перезапуск служб. По функционалу, как я понял, вы хотите только функцию обновления агента- т.е только замену zabbix_agentd.exe на некую эталонную в рамках жизненного цикла вашей версии заббикс.  
Вы согласны со всем вышеперечисленным? Если да, то какое событие должно запускать обновление - несоответствие версии агент\сервер?
И, конечно, все вышеперечисленное верно для хостов на MS OS, о Xnix разговор не идет.

**Comment by SergeBrick** [comment]
Да, верно. Системы только MS Windows. Событие - можно проверять на сайте производителя
последнюю актуальную версию и сравнивать с текущей.

**Comment by VladimirKosyuk** [comment]
Хорошо, напишите ваш email(у меня нет телеграм) и обсудим ТРЗ и остальное. По задаче выше, исходя из требований - она реализуема, но нужно обсудить детали.

**Comment by SergeBrick** [comment]
bserge gav programist tchk ru

**Comment by VladimirKosyuk** [comment]
Такое сложно перевести в smtp, короче - я не понял. Напишите в формате yyy@xxx.ru

**Comment by SergeBrick** [comment]
bserge@programist.ru

**Comment by VladimirKosyuk** [comment]
Закрываю Issue, общение через direct. Сама ветка багом не является.
